sudo: false
language: python
env:
   global:
      - secure: "BQ6qt3AOkcapuzOAkct8LbpyF3MngFk/+v/HlSg9Cxfo1CrYZOuwzemLI+pXKTbJiJcUF2UbooaoQANk9uKc9/NZfBdWG8NRncV+c3QGceWJTU7NaDle04Gp1cmnH6a7YRWN652xaPa80vlM/hMtCLg9zSnk6HQXNlTcdrfzWus="
      - GH_DOC_BRANCH: master
      - GH_REPOSITORY: github.com/MDAnalysis/GridDataFormats.git
      - GIT_CI_USER: TravisCI
      - GIT_CI_EMAIL: TravisCI@mdanalysis.org
      - MDA_DOCDIR: build/sphinx/html
      - CONDA_DEPENDENCIES="numpy scipy pytest pytest-cov sphinx"
      - PIP_DEPENDENCIES="codecov sphinx-sitemap"
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda create --yes -q -n pyenv python=$TRAVIS_PYTHON_VERSION $CONDA_DEPENDENCIES
  - source activate pyenv
  - pip install ${PIP_DEPENDENCIES}
  - pip install -v ./
script:
  - pytest --cov=gridData ./gridData/tests
  - |
     test ${TRAVIS_PULL_REQUEST} == "false" && \
     test ${TRAVIS_BRANCH} == ${GH_DOC_BRANCH} && \
     test "${TRAVIS_BUILD_NUMBER}.1" == "${TRAVIS_JOB_NUMBER}" && \
     python setup.py build_sphinx || \
     true
after_success:
  - codecov
  - |
     test ${TRAVIS_PULL_REQUEST} == "false" && \
     test ${TRAVIS_BRANCH} == ${GH_DOC_BRANCH} && \
     test "${TRAVIS_BUILD_NUMBER}.1" == "${TRAVIS_JOB_NUMBER}" && \
     bash ./ci/deploy_docs.sh
