name: Build and upload to PyPi

on:
  push:
    tags:
      - "*"
  release:
    types:
      - published

jobs:
  pypi_push:
    environment: deploy
    if: "github.repository == 'MDAnalysis/GridDataFormats'"
    name: Build, upload and test pure Python wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: testpypi_deploy
        uses: MDAnalysis/pypi-deployment@main
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          test_submission: true
          package_name: 'gridData'

      - name: pypi_deploy
        uses: MDAnalysis/pypi-deployment@main
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          token: ${{ secrets.PYPI_API_TOKEN }}
          package_name: 'gridData'
